### ISSUE TITLE
error in "viralAssociationPipeline.py"

### ISSUE THREAD

**Issue by Jigyasa3** [njdbickhart/RumenLongReadASM#2]
hey @njdbickhart !

I am getting the following error when I run the complete pipeline-
`Traceback (most recent call last):
  File "/bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/RumenLongReadASM/viralAssociationPipeline.py", line 542, in <module>
    main(args)
  File "/bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/RumenLongReadASM/viralAssociationPipeline.py", line 120, in main
    args.output + '.algn.viruses', oThresh = args.overhang)
  File "/bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/RumenLongReadASM/viralAssociationPipeline.py", line 446, in alignECReads
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, encoding='utf8')
  File "/apps/free81/python/3.7.3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/apps/free81/python/3.7.3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/j/jigyasa-arora/local/minimap2'
`

Mycode-
`python3 ${SOFT_DIR3}/viralAssociationPipeline.py -l ${IN_DIR}/SRR8266664_subreads.fastq -a ${IN_DIR}/2-rumen_illuminaR3PCRFree_megahit.final.contigs.fa -g ${IN_DIR}/viral-contigs.fasta -b ${IN_DIR}/2-contigs_supplementary_table_7_long_read_taxonomy.csv -v ${IN_DIR}/viral-contigs-length.txt -c 2.5 -e 150 -o viral.python -m /home/j/jigyasa-arora/local/minimap2 -s /apps/free72/samtools/1.9/bin`

I am using the data from your rumen metagenome paper. 
a)SRR8266664_subreads.fastq - FastQ reads from the Bioproject.
b)2-rumen_illuminaR3PCRFree_megahit.final.contigs.fa- I just changed the Fasta headers to look like this-
`>k127_21
AATTATGAAAGTTTACCAAGATTATGTAAATATTATGAATTAAAGGAGGATAACAATGAGATATCAACTAATAAATCCAATTAATCCAAAATATTCTACAATAGAAACAATATTAACAAATAGACATATTCCACTTGCGGAAGTGTCTCATTATTTAAATACCACTGATGAAGATATTAATAAGCCAGAAGCATTTGGTCAAAATTGTTTGACACAAGCCGCTCAATGTTTAATACAACACATTGCTGCGGGAAGT`
c)viral-contigs.fasta-370 viral contains in the same format as (b)
d)2-contigs_supplementary_table_7_long_read_taxonomy.csv- I modified the "supplementary_table_7_long_read_taxonomy.tab" to extract out contig and taxonomy info-
`#IlluminaCtgAligns      superkingdom.t.24       phylum.t.28     order.t.32      family.t.36     genus.t.40      species.t.44
k127_658417     Bacteria        Proteobacteria  Vibrionales     Vibrionaceae    Photobacterium  Photobacterium angustum
k127_1194236    Bacteria        Proteobacteria  Vibrionales     Vibrionaceae    Photobacterium  Photobacterium angustum
k127_1282286    Bacteria        Proteobacteria  Vibrionales     Vibrionaceae    Photobacterium  Photobacterium angustum
`
e)viral-contigs-length.txt- tab delimited length info of viral contigs
`k127_1810\t5326
k127_2123\t1009
k127_7856\t2862
k127_15033\t5663
`
I have tested minimap2, and the software should work.
I am running the codes on a computing cluster where I don't have root access.
If you need any more info, then please let me know.

Thanks again!

**Comment by njdbickhart** [comment]
Hello @Jigyasa3 , the error message suggests that the "minimap2" executable doesn't have the correct permissions to execute (ie. "`chmod +x`"). Can you post a "`ls -hal /home/j/jigyasa-arora/local/minimap2`"? 

Also, you mentioned that you are working on a cluster. Are you submitting this job through Slurm or SGE?

**Comment by Jigyasa3** [comment]
Hey @njdbickhart 
Thank you so much for replying!

Here are the permission details-
`-rwxrwxrwx 1 jigyasa-arora mikheyevuni 1.4M Jul 31 18:48 minimap2`

"minimap2" should be executable, I used it to generate the "ec_virus_long_read_alignments.paf" file.

I am using SLURM to submit jobs on the cluster.
Let me know if need more details from me.

**Comment by Jigyasa3** [comment]
It works! Sorry, my fastq file was in the read-only folder. Thanks for all the help though!

**Comment by njdbickhart** [comment]
I'm glad to hear that it works! Good luck and I hope you find something interesting!
